# Generated by Django 6.0.5 on 2026-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tagline', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
