# Generated by Django 6.0.5 on 2026-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
