# Generated by Django 6.0.5 on 2026-05-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='base_price',
        ),
    ]
