# Generated by Django 6.0.5 on 2026-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_price_car_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='no_background_image',
            field=models.CharField(default='rs.png'),
            preserve_default=False,
        ),
    ]
