# Generated by Django 6.0.5 on 2026-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_car_no_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(to='base.colors'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ManyToManyField(to='base.engine'),
        ),
    ]
