# Generated by Django 6.0.5 on 2026-05-31 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_colors_engine_remove_car_power_car_color_car_engine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
