# Generated by Django 6.0.5 on 2026-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_colors_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='tagline',
        ),
    ]
