# Generated by Django 6.0.5 on 2026-05-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_equipment_remove_car_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
    ]
