# Generated by Django 6.0.5 on 2026-05-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_car_color_remove_car_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine',
            field=models.FloatField(),
        ),
    ]
